version: "3.8"

services:
  kong:
    container_name: kong
    image: kong:alpine
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    command: kong start
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DECLARATIVE_CONFIG=/opt/kong/kong.yml
    volumes:
      - ./kong.yml:/opt/kong/kong.yml

  # log:
  #   container_name: log-nestjs
  #   image: log
  #   build:
  #     context: ./log
  #     dockerfile: Dockerfile.dev # development
  #   environment: # local
  #     - DATABASE_URL=postgresql://${LOG_POSTGRES_USER:?}:${LOG_POSTGRES_PASSWORD:?}@log-postgres:5432/log?schema=public
  #     - RB_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - QUEUE=log
  #   volumes:
  #     - ./log:/app
  #   depends_on:
  #     - rabbitmq
  #     - log-postgres

  # cfg:
  #   container_name: cfg-nestjs
  #   image: cfg
  #   build:
  #     context: ./config
  #     dockerfile: Dockerfile.dev # development
  #   environment: # local
  #     - DATABASE_URL=postgresql://${CFG_POSTGRES_USER:?}:${CFG_POSTGRES_PASSWORD:?}@cfg-postgres:5432/cfg?schema=public
  #     - RB_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - QUEUE=cfg
  #     - LOG_RB_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - LOG_QUEUE=log
  #     - USER_RB_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - USER_QUEUE=user
  #   volumes:
  #     - ./config:/app
  #   depends_on:
  #     - rabbitmq
  #     - cfg-postgres

  unit:
    container_name: unit-nestjs
    image: unit
    build:
      context: ./unit
      dockerfile: Dockerfile.dev # development
    environment: # local
      - DATABASE_URL=postgresql://${UNIT_POSTGRES_USER:?}:${UNIT_POSTGRES_PASSWORD:?}@unit-postgres:5432/unit?schema=public
      - RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
      - QUEUE=unit
      - LOG_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
      - LOG_QUEUE=log
    volumes:
      - ./unit:/app

  # company:
  #   container_name: company-nestjs
  #   image: company
  #   build:
  #     context: ./company
  #     dockerfile: Dockerfile.dev # development
  #   environment: # local
  #     - DATABASE_URL=postgresql://${COM_POSTGRES_USER:?}:${COM_POSTGRES_PASSWORD:?}@company-postgres:5432/company?schema=public
  #     - RB_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - QUEUE=company
  #     - LOG_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
  #     - LOG_QUEUE=log
  #     - UNIT_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
  #     - UNIT_QUEUE=unit
  #   volumes:
  #     - ./company:/app
  #   depends_on:
  #     - rabbitmq
  #     - company-postgres

  user:
    container_name: user-nestjs
    image: user
    build:
      context: ./user
      dockerfile: Dockerfile.dev # development
    environment: # local
      - DATABASE_URL=postgresql://${USER_POSTGRES_USER:?}:${USER_POSTGRES_PASSWORD:?}@user-postgres:5432/user?schema=public
      - RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
      - QUEUE=user
      - LOG_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
      - LOG_QUEUE=log
      - CFG_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
      - CFG_QUEUE=cfg
    volumes:
      - ./user:/app

  # map:
  #   container_name: map-nestjs
  #   image: map
  #   build:
  #     context: ./map
  #     dockerfile: Dockerfile.dev # development
  #   environment: # local
  #     - DATABASE_URL=postgresql://${MAP_POSTGRES_USER:?}:${MAP_POSTGRES_PASSWORD:?}@map-postgres:5432/map?schema=public
  #     - RB_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
  #     - QUEUE=map
  #     - LOG_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
  #     - LOG_QUEUE=log
  #     - UNIT_RB_URL=amqp://${RABBITMQ_DEFAULT_USER:?}:${RABBITMQ_DEFAULT_PASS:?}@rabbitmq:5672
  #     - UNIT_QUEUE=unit
  #   volumes:
  #     - ./map:/app
  #   depends_on:
  #     - rabbitmq
  #     - map-postgis
